/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTransporterRouteImport } from './routes/_authenticated/transporter'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedMastersRouteImport } from './routes/_authenticated/masters'
import { Route as AuthenticatedLedgerRouteImport } from './routes/_authenticated/ledger'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedInquiriesRouteImport } from './routes/_authenticated/inquiries'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedInvoicesInvoiceIdRouteImport } from './routes/_authenticated/invoices.$invoiceId'
import { Route as AuthenticatedAdminPlansRouteImport } from './routes/_authenticated/admin/plans'
import { Route as AuthenticatedAdminCompaniesRouteImport } from './routes/_authenticated/admin/companies'
import { Route as AuthenticatedOrdersOrderIdBiltyRouteImport } from './routes/_authenticated/orders.$orderId.bilty'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransporterRoute =
  AuthenticatedTransporterRouteImport.update({
    id: '/transporter',
    path: '/transporter',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMastersRoute = AuthenticatedMastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLedgerRoute = AuthenticatedLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInquiriesRoute = AuthenticatedInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesInvoiceIdRoute =
  AuthenticatedInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedAdminPlansRoute = AuthenticatedAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCompaniesRoute =
  AuthenticatedAdminCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedOrdersOrderIdBiltyRoute =
  AuthenticatedOrdersOrderIdBiltyRouteImport.update({
    id: '/$orderId/bilty',
    path: '/$orderId/bilty',
    getParentRoute: () => AuthenticatedOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/inquiries': typeof AuthenticatedInquiriesRoute
  '/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/ledger': typeof AuthenticatedLedgerRoute
  '/masters': typeof AuthenticatedMastersRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transporter': typeof AuthenticatedTransporterRoute
  '/users': typeof AuthenticatedUsersRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/orders/$orderId/bilty': typeof AuthenticatedOrdersOrderIdBiltyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/inquiries': typeof AuthenticatedInquiriesRoute
  '/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/ledger': typeof AuthenticatedLedgerRoute
  '/masters': typeof AuthenticatedMastersRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transporter': typeof AuthenticatedTransporterRoute
  '/users': typeof AuthenticatedUsersRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/orders/$orderId/bilty': typeof AuthenticatedOrdersOrderIdBiltyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/inquiries': typeof AuthenticatedInquiriesRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/_authenticated/ledger': typeof AuthenticatedLedgerRoute
  '/_authenticated/masters': typeof AuthenticatedMastersRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/transporter': typeof AuthenticatedTransporterRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/_authenticated/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/_authenticated/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/_authenticated/orders/$orderId/bilty': typeof AuthenticatedOrdersOrderIdBiltyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/expenses'
    | '/inquiries'
    | '/invoices'
    | '/ledger'
    | '/masters'
    | '/orders'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/transporter'
    | '/users'
    | '/admin/companies'
    | '/admin/plans'
    | '/invoices/$invoiceId'
    | '/orders/$orderId/bilty'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/expenses'
    | '/inquiries'
    | '/invoices'
    | '/ledger'
    | '/masters'
    | '/orders'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/transporter'
    | '/users'
    | '/admin/companies'
    | '/admin/plans'
    | '/invoices/$invoiceId'
    | '/orders/$orderId/bilty'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/expenses'
    | '/_authenticated/inquiries'
    | '/_authenticated/invoices'
    | '/_authenticated/ledger'
    | '/_authenticated/masters'
    | '/_authenticated/orders'
    | '/_authenticated/payments'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/transporter'
    | '/_authenticated/users'
    | '/_authenticated/admin/companies'
    | '/_authenticated/admin/plans'
    | '/_authenticated/invoices/$invoiceId'
    | '/_authenticated/orders/$orderId/bilty'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transporter': {
      id: '/_authenticated/transporter'
      path: '/transporter'
      fullPath: '/transporter'
      preLoaderRoute: typeof AuthenticatedTransporterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masters': {
      id: '/_authenticated/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof AuthenticatedMastersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ledger': {
      id: '/_authenticated/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AuthenticatedLedgerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inquiries': {
      id: '/_authenticated/inquiries'
      path: '/inquiries'
      fullPath: '/inquiries'
      preLoaderRoute: typeof AuthenticatedInquiriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices/$invoiceId': {
      id: '/_authenticated/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthenticatedInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/admin/plans': {
      id: '/_authenticated/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/companies': {
      id: '/_authenticated/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/orders/$orderId/bilty': {
      id: '/_authenticated/orders/$orderId/bilty'
      path: '/$orderId/bilty'
      fullPath: '/orders/$orderId/bilty'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdBiltyRouteImport
      parentRoute: typeof AuthenticatedOrdersRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCompaniesRoute: typeof AuthenticatedAdminCompaniesRoute
  AuthenticatedAdminPlansRoute: typeof AuthenticatedAdminPlansRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCompaniesRoute: AuthenticatedAdminCompaniesRoute,
  AuthenticatedAdminPlansRoute: AuthenticatedAdminPlansRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedInvoicesRouteChildren {
  AuthenticatedInvoicesInvoiceIdRoute: typeof AuthenticatedInvoicesInvoiceIdRoute
}

const AuthenticatedInvoicesRouteChildren: AuthenticatedInvoicesRouteChildren = {
  AuthenticatedInvoicesInvoiceIdRoute: AuthenticatedInvoicesInvoiceIdRoute,
}

const AuthenticatedInvoicesRouteWithChildren =
  AuthenticatedInvoicesRoute._addFileChildren(
    AuthenticatedInvoicesRouteChildren,
  )

interface AuthenticatedOrdersRouteChildren {
  AuthenticatedOrdersOrderIdBiltyRoute: typeof AuthenticatedOrdersOrderIdBiltyRoute
}

const AuthenticatedOrdersRouteChildren: AuthenticatedOrdersRouteChildren = {
  AuthenticatedOrdersOrderIdBiltyRoute: AuthenticatedOrdersOrderIdBiltyRoute,
}

const AuthenticatedOrdersRouteWithChildren =
  AuthenticatedOrdersRoute._addFileChildren(AuthenticatedOrdersRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedInquiriesRoute: typeof AuthenticatedInquiriesRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRouteWithChildren
  AuthenticatedLedgerRoute: typeof AuthenticatedLedgerRoute
  AuthenticatedMastersRoute: typeof AuthenticatedMastersRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRouteWithChildren
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTransporterRoute: typeof AuthenticatedTransporterRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedInquiriesRoute: AuthenticatedInquiriesRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRouteWithChildren,
  AuthenticatedLedgerRoute: AuthenticatedLedgerRoute,
  AuthenticatedMastersRoute: AuthenticatedMastersRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRouteWithChildren,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTransporterRoute: AuthenticatedTransporterRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
